[lattice]

dimension       = 2

lattice_vectors = [[1.0, 0.0],
                   [0.5, 0.8660254037844386]]

basis_vectors   = [[0.0, 0.0],
                   [0.5, 0.0],
                   [0.25, 0.4330127018922193]]

lattice_size    = [5, 5]


[model]

# Nearest neighbor pair interaction
[[model.pair]]
strength = 2.0
dist     = 1

# Three-hop next-next-nearest neighbor pair interaction
[[model.pair]]
strength = 0.5
dist     = 3
class    = 2

# External field along z axis
[[model.field]]
strength = -2.0

# Long-range dipole interaction
[[model.dipole]]
strength = 4.0